### Data Exploration with Pandas

In [2]:
# Imports
import pandas as pd

In [3]:
# Import data
car_sales = pd.read_csv("data/car_prices.csv")

In [4]:
car_sales.head()

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
0,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg566472,ca,5.0,16639.0,white,black,kia motors america inc,20500.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
1,2015,Kia,Sorento,LX,SUV,automatic,5xyktca69fg561319,ca,5.0,9393.0,white,beige,kia motors america inc,20800.0,21500.0,Tue Dec 16 2014 12:30:00 GMT-0800 (PST)
2,2014,BMW,3 Series,328i SULEV,Sedan,automatic,wba3c1c51ek116351,ca,45.0,1331.0,gray,black,financial services remarketing (lease),31900.0,30000.0,Thu Jan 15 2015 04:30:00 GMT-0800 (PST)
3,2015,Volvo,S60,T5,Sedan,automatic,yv1612tb4f1310987,ca,41.0,14282.0,white,black,volvo na rep/world omni,27500.0,27750.0,Thu Jan 29 2015 04:30:00 GMT-0800 (PST)
4,2014,BMW,6 Series Gran Coupe,650i,Sedan,automatic,wba6b2c57ed129731,ca,43.0,2641.0,gray,black,financial services remarketing (lease),66000.0,67000.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)

In [5]:
car_sales.shape, car_sales.dtypes

((558837, 16),
 year              int64
 make                str
 model               str
 trim                str
 body                str
 transmission        str
 vin                 str
 state               str
 condition       float64
 odometer        float64
 color               str
 interior            str
 seller              str
 mmr             float64
 sellingprice    float64
 saledate            str
 dtype: object)

In [6]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 558837 entries, 0 to 558836
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   year          558837 non-null  int64
 1   make          548536 non-null  str
 2   model         548438 non-null  str
 3   trim          548186 non-null  str
 4   body          545642 non-null  str
 5   transmission  493485 non-null  str
 6   vin           558833 non-null  str
 7   state         558837 non-null  str
 8   condition     547017 non-null  float64
 9   odometer      558743 non-null  float64
 10  color         558088 non-null  str
 11  interior      558088 non-null  str
 12  seller        558837 non-null  str
 13  mmr           558799 non-null  float64
 14  sellingprice  558825 non-null  float64
 15  saledate      558825 non-null  str
dtypes: float64(4), int64(1), str(11)
memory usage: 68.2 MB

In [7]:
car_sales.loc[1000:1003, "body"]

1000        Sedan
1001          SUV
1002          SUV
1003    Hatchback
Name: body, dtype: str

In [8]:
car_sales.iloc[23:31]

,year,make,model,trim,body,transmission,vin,state,condition,odometer,color,interior,seller,mmr,sellingprice,saledate
23,2015,Audi,A3,1.8 TFSI Premium,Sedan,automatic,wauacgff7f1002327,ca,49.0,5826.0,gray,black,audi north scottsdale,24000.0,23750.0,Thu Dec 18 2014 12:30:00 GMT-0800 (PST)
24,2014,BMW,6 Series,650i,Convertible,automatic,wbayp9c57ed169262,ca,38.0,10736.0,black,black,the hertz corporation,67000.0,65000.0,Tue Jan 06 2015 12:30:00 GMT-0800 (PST)
25,2015,Hyundai,Sonata,SE,Sedan,automatic,5npe24af4fh038482,ca,NaN,9281.0,silver,gray,enterprise vehicle exchange / tra / rental / t...,15150.0,8500.0,Tue Dec 16 2014 13:00:00 GMT-0800 (PST)
26,2015,Volvo,XC70,T6,Wagon,automatic,yv4902nb3f1198103,ca,42.0,16506.0,brown,brown,volvo na rep/world omni,32100.0,32500.0,Thu Feb 26 2015 04:30:00 GMT-0800 (PST)
27,2015,Volvo,XC70,T6,Wagon,automatic,yv4902nb3f1196951,ca,48.0,12725.0,beige,beige,volvo na rep/world omni,32300.0,32500.0,Thu Feb 12 2015 04:30:00 GMT-0800 (PST)
28,2014,BMW,X5,sDrive35i,SUV,automatic,5uxkr2c52e0h33130,ca,NaN,11278.0,gray,black,avis rac/san leandro,50400.0,34000.0,Tue Dec 16 2014 13:00:00 GMT-0800 (PST)
29,2014,Chevrolet,Camaro,LT,Coupe,automatic,2g1fb1e35e9238302,ca,42.0,11874.0,gray,black,midway hfc fleet/ars,22200.0,19500.0,Thu Dec 18 2014 12:00:00 GMT-0800 (PST)
30,2014,Chevrolet,Cruze,1LT,Sedan,automatic,1g1pc5sb2e7105471,ca,42.0,37888.0,gray,black,enterprise vehicle exchange/orange,11600.0,11500.0,Tue Dec 30 2014 12:30:00 GMT-0800 (PST)

In [9]:
car_sales.loc[25000:25005, "make"]

25000    Pontiac
25001    Pontiac
25002     Saturn
25003     Saturn
25004     Saturn
25005     Toyota
Name: make, dtype: str

In [10]:
# Columns with missing values 
car_sales.isna().sum()

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65352
vin                 4
state               0
condition       11820
odometer           94
color             749
interior          749
seller              0
mmr                38
sellingprice       12
saledate           12
dtype: int64

In [11]:
 #Dropping rows with missing columns 
 car_sales = car_sales.dropna(subset=["sellingprice", "saledate", "vin", "mmr"])

I dropped these items because they are very critical for the model i want to build, hence it will be misleading for me to make an assumption for them

In [12]:
car_sales.isna().sum()

year                0
make            10301
model           10399
trim            10651
body            13195
transmission    65351
vin                 0
state               0
condition       11794
odometer           94
color             749
interior          749
seller              0
mmr                 0
sellingprice        0
saledate            0
dtype: int64

In [13]:
# Filling missing columns 

# Categorical columns
cat_cols = ["make", "model", "trim", "body", "transmission", "color", "interior"]

car_sales[cat_cols] = car_sales[cat_cols].fillna("missing")

All non-numerical columns have been filled with "missing"

In [14]:
car_sales.isna().sum()

year                0
make                0
model               0
trim                0
body                0
transmission        0
vin                 0
state               0
condition       11794
odometer           94
color               0
interior            0
seller              0
mmr                 0
sellingprice        0
saledate            0
dtype: int64

In [15]:
# Filling missing values in the odometer column with the median

car_sales["odometer"] = car_sales["odometer"]. fillna(car_sales["odometer"].median())

In [16]:
# Fill missing values in condition with median

car_sales["condition"] = car_sales["condition"]. fillna(
    car_sales["condition"].median())

In [17]:
car_sales.isna().sum()

year            0
make            0
model           0
trim            0
body            0
transmission    0
vin             0
state           0
condition       0
odometer        0
color           0
interior        0
seller          0
mmr             0
sellingprice    0
saledate        0
dtype: int64

In [18]:
car_sales.shape

(558799, 16)

In [19]:
# Group data by a category col

car_sales.groupby("make")["sellingprice"].agg(["mean", "sum", "count"])

                      mean          sum  count
make
Acura         14017.268260   82715900.0   5901
Aston Martin  54812.000000    1370300.0     25
Audi          19915.432782  116883675.0   5869
BMW           21441.895748  444254638.0  20719
Bentley       74367.672414    8626650.0    116
...                    ...          ...    ...
subaru         3710.416667     222625.0     60
suzuki         4810.000000      24050.0      5
toyota         7339.105263     697215.0     95
volkswagen     6145.833333     147500.0     24
vw            13672.916667     328150.0     24

[97 rows x 3 columns]

In [22]:
# Pipeline with at least 4 chained methods

#load data
car_sales_2 = pd.read_csv("data/car_prices.csv")

#Chaining
car_sales_2 = (
    car_sales_2
    .dropna(subset=["sellingprice"])
    .assign(condition=lambda df: df["condition"].fillna(df["condition"].median()))
    .query("odometer < 50000")
    .reset_index()
)

In [23]:
car_sales_2.isna().sum()

index               0
year                0
make             1543
model            1641
trim             1591
body             1803
transmission    34801
vin                 4
state               0
condition           0
odometer            0
color             519
interior          519
seller              0
mmr                26
sellingprice        0
saledate            0
dtype: int64